/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'quantity' : IDL.Nat,
  'menuItemId' : IDL.Nat,
});
export const Bill = IDL.Record({
  'id' : IDL.Nat,
  'paymentStatus' : IDL.Text,
  'orderId' : IDL.Nat,
  'totalAmount' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const Time = IDL.Int;
export const RestaurantOrder = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'createdAt' : Time,
  'tableId' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
});
export const Reservation = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'guestCount' : IDL.Nat,
  'tableId' : IDL.Nat,
  'guestName' : IDL.Text,
  'dateTime' : Time,
});
export const Table = IDL.Record({
  'id' : IDL.Nat,
  'occupied' : IDL.Bool,
  'number' : IDL.Nat,
  'capacity' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMenuItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addTable' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBill' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'createOrder' : IDL.Func([IDL.Nat, IDL.Vec(OrderItem)], [IDL.Nat], []),
  'getBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalTables' : IDL.Nat,
          'todayReservations' : IDL.Nat,
          'activeOrders' : IDL.Nat,
          'totalRevenue' : IDL.Nat,
          'occupiedTables' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(RestaurantOrder)], ['query']),
  'getReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'getTables' : IDL.Func([], [IDL.Vec(Table)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'makeReservation' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, Time],
      [IDL.Nat],
      [],
    ),
  'markBillPaid' : IDL.Func([IDL.Nat], [], []),
  'removeTable' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setTableOccupied' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'toggleMenuItemAvailability' : IDL.Func([IDL.Nat], [], []),
  'updateMenuItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateReservationStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'quantity' : IDL.Nat,
    'menuItemId' : IDL.Nat,
  });
  const Bill = IDL.Record({
    'id' : IDL.Nat,
    'paymentStatus' : IDL.Text,
    'orderId' : IDL.Nat,
    'totalAmount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Time = IDL.Int;
  const RestaurantOrder = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'createdAt' : Time,
    'tableId' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
  });
  const Reservation = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'guestCount' : IDL.Nat,
    'tableId' : IDL.Nat,
    'guestName' : IDL.Text,
    'dateTime' : Time,
  });
  const Table = IDL.Record({
    'id' : IDL.Nat,
    'occupied' : IDL.Bool,
    'number' : IDL.Nat,
    'capacity' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMenuItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addTable' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBill' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'createOrder' : IDL.Func([IDL.Nat, IDL.Vec(OrderItem)], [IDL.Nat], []),
    'getBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalTables' : IDL.Nat,
            'todayReservations' : IDL.Nat,
            'activeOrders' : IDL.Nat,
            'totalRevenue' : IDL.Nat,
            'occupiedTables' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(RestaurantOrder)], ['query']),
    'getReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'getTables' : IDL.Func([], [IDL.Vec(Table)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'makeReservation' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, Time],
        [IDL.Nat],
        [],
      ),
    'markBillPaid' : IDL.Func([IDL.Nat], [], []),
    'removeTable' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setTableOccupied' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'toggleMenuItemAvailability' : IDL.Func([IDL.Nat], [], []),
    'updateMenuItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateReservationStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };