/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bill {
  'id' : bigint,
  'paymentStatus' : string,
  'orderId' : bigint,
  'totalAmount' : bigint,
}
export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'category' : string,
  'price' : bigint,
}
export interface OrderItem { 'quantity' : bigint, 'menuItemId' : bigint }
export interface Reservation {
  'id' : bigint,
  'status' : string,
  'guestCount' : bigint,
  'tableId' : bigint,
  'guestName' : string,
  'dateTime' : Time,
}
export interface RestaurantOrder {
  'id' : bigint,
  'status' : string,
  'createdAt' : Time,
  'tableId' : bigint,
  'totalAmount' : bigint,
  'items' : Array<OrderItem>,
}
export interface Table {
  'id' : bigint,
  'occupied' : boolean,
  'number' : bigint,
  'capacity' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMenuItem' : ActorMethod<[string, string, bigint, string], bigint>,
  'addTable' : ActorMethod<[bigint, bigint], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBill' : ActorMethod<[bigint], bigint>,
  'createOrder' : ActorMethod<[bigint, Array<OrderItem>], bigint>,
  'getBills' : ActorMethod<[], Array<Bill>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'totalTables' : bigint,
      'todayReservations' : bigint,
      'activeOrders' : bigint,
      'totalRevenue' : bigint,
      'occupiedTables' : bigint,
    }
  >,
  'getMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getOrders' : ActorMethod<[], Array<RestaurantOrder>>,
  'getReservations' : ActorMethod<[], Array<Reservation>>,
  'getTables' : ActorMethod<[], Array<Table>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'makeReservation' : ActorMethod<[bigint, string, bigint, Time], bigint>,
  'markBillPaid' : ActorMethod<[bigint], undefined>,
  'removeTable' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setTableOccupied' : ActorMethod<[bigint, boolean], undefined>,
  'toggleMenuItemAvailability' : ActorMethod<[bigint], undefined>,
  'updateMenuItem' : ActorMethod<
    [bigint, string, string, bigint, string],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
  'updateReservationStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];